[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "7aeddb8a2714b3e4dc1540836332d233e012cc0d"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual.download]]
    sha256 = "a6bc45c8d489a8d7de37187265891f335482fa15ac8c0ddfde791bdeb8e36668"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "647ac6b31dcaf3f1d00e4cb7e3b64535dfec5c32"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual.download]]
    sha256 = "fad62d8b8a7f65284aa71759624119ee946a0e69ca0316de98a147324417c046"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "33a6c6d6fc9f5eb9bfc303c3d2b7326d5e93e0de"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual.download]]
    sha256 = "ae0332cb8fd45707490ea31c46327f63ceccd2484f502b9a3b0c9addf1f8af40"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "9f4b793deb1549af3b8e5370c64fd960fb5933c6"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual.download]]
    sha256 = "c3f72a05ec4fc361330e37b9d470f92ac7b9cc5233e9cfbd8533b23912d36ab6"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"

[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "96d89c63b47d15497b9c7c2ac7258ec8ab018b06"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "7aa21c362545c02e663f11a0702a9de138aff0fdabef109a8c9c55a115014dea"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "1119461b6c7dcab0e197d9076928c0226024170c"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "b7f4033db30504e104c4983fcda205aaae2e1312792caa31a93efd639df6d262"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "15c5e638e00683cee24f3d3f7e2ecb0079c89a2f"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "d13fcf156a7546a03738e99cdb23d37af70dac28c8690eafd4903f205cd472dd"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "e9d8ce550cb4e2aa36868676ec27d776090afbf3"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "54103959756d110c1bd5c64a0d543075ecc6a1969632f6fc78df25d49d453434"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"

[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "6ece6f011688e144b2e7331bce07beadcc557e4a"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "a9b887e329db4d28ae13038f0928611b674ec9e2b08bbec025fc4bf5a5979609"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "bd55123daba386ee074b62b798d016a0ce81afc8"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "f0204a69a3fb4df3b912a8c35141572dc7b497bc53d04214d35233472b814e0f"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c3499f5a4e7f2d5fbe3dcfbfc31f748e8c421bad"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "bc4de5008efa1d3962f32f9375ff1b6227df666f7b11e95b2a3734015dac4145"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "43c7d7b458667a256a7cdbd4e43d9fcf349c5a78"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "12fed1d7943adfa633ed60f9e9d114d20bc89e54a6462ea23f3fef7e004ce974"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"
