[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "6630e19dbb0f2d4a194897f20d0d7c1cc534da04"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual.download]]
    sha256 = "ff8d61ac4b18d2b83607cf659671cf40f662b1937137514d4d42456fdfa729b0"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "2af7fe068cae0c66c5fa15523098a5fe7b083e4f"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual.download]]
    sha256 = "a28707752de86e5274b52c63fd66da0cf46e5a359982387ed46545fb3c279457"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "33a6c6d6fc9f5eb9bfc303c3d2b7326d5e93e0de"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual.download]]
    sha256 = "4c604b1706aa0379d9771ca810b191832a65b789a27db970dd619ae2fc55898d"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "9f4b793deb1549af3b8e5370c64fd960fb5933c6"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual.download]]
    sha256 = "d24b8cf4bf26c719f12d526852093597293f84f56ecbb1c503109cecc2c2a1cf"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"

[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "59297f98e1dc53e791d89ddba3a9eb8306234cc7"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "7c8e80b3b26eae67a360a489d69db76231bc989582d3115410ba4708c9e6f907"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "3c39c566435d212699d98bdde06bfcc5b215a624"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "4c0682f8ca057da2b86a14a9cbb52cedd2d21b64e2393651bef532f9a731d42b"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "4e9ad5c18affa1bdcc5aabdf30f0704526a3e796"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "98dca8c9e12c3579a516efd4d4f6f5a9ca1d34c7209b08bf10ed49db821fa590"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "c6e8be88a1e1f95d25a1c6fecaa05e1b55709ef5"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "4d9fd9d23d345fbbb7cc5c7b9d6b4bf99da344dc27a682425d194a0eeab49025"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"

[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "caed37b54bf508a8cfcc8e86d1455dbf63d50ec7"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "3a8be3c5d26c4f7fb8cace1886423af37427a4cfc2df710bd77702e581a4d84f"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b298f3fdc81c7db20d6fb30c8e2aea5e26ee5542"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "c9a0dd2b5441b2c819b6fbecc0d27bd1469117e30d92923c1883a26cd3d2d972"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "5220ecbc04474a6a7f7e5497e99164171874377f"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "aa07371c9f51bcad170eb01422649539f2da37fee870cc72b9b8681ec2de28ab"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "97164a229d25d8aa0ae40741665c39a63fb1b79e"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "90a7cb685e2cd0cda10790be8a893293d6691cb705ac98118bad49036364b4cb"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"
