[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "ad8038d596b45005e66bdb250c811bd23945181a"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual.download]]
    sha256 = "fd4efbc6cbec10ac3e59ca5d6fbf1243f4053b7509de86e22e843a0d2677c960"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "c05c7cf5be3a4e57e338911592716d4b9eb1805d"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual.download]]
    sha256 = "d00f01e3673f57cb4d25cf085ac65c8a0a4f75435fa49e6d83aee94851499f8e"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "33a6c6d6fc9f5eb9bfc303c3d2b7326d5e93e0de"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual.download]]
    sha256 = "190baa7c530c970f3ccc9540a5e991e2141c0fbfe816a215313a538151bb8a44"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "9f4b793deb1549af3b8e5370c64fd960fb5933c6"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual.download]]
    sha256 = "8f6e1740cb00f429eef51359f6d0a67a72d09c62cf46914d17f00a018a330f36"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"

[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "0204cadc13f0715493e2be0f9b7a8291a854083a"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "ffcdd8395406c1407f379e240e2fb399f51c80115f7243741c58dde6a820c93b"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "b4dc13f6f6f6810bbfb90dfbf9cc50ca7ec2a559"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "04b215c4928eb64dbe97ed1215baeec905d78bf0dce5aea9043401ba9c35a3d9"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "ec9d2a119ca5091ea2861733f1db8ba1ce6d3ec6"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "005f367738ab4f81a06fface51b23d5d54d7acd81798722d8c44602e8b7073b5"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "1940e756bd79e1906b5c128fc1a29267977b65c8"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "c96c5a682bbf5053ddb0fcfcacab5bfa469692e1909a3fc3e95f6d01ad246f8b"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"

[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "9473cd1356eb53f618772439d08ff5ee0078b726"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "a237235109dc9d8d5e67988ff4dfd015e33cbd499999c939e6da8306d1f988bc"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "17d8824008a356c94aabddc043e63a2d2a728ba7"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "dc6c2c96932a867d3c88b8aee4051f9eeb7fdd577fd647a170c1f1d8efd861f2"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "3784a92c9124ffee9a27bcfda23d034c81f6dfae"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "92fb32808c248015e3dacf964d8beb0dfe452e08f555e50a861a5b35090ccda1"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "df16bc3b7bf482c2af4b2df2e54c24273743243c"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "e5323447693045f885c14fc784dd290b7dc699e3606bafd34a0e1dc76d517d83"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"
