[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "6447e693c43dd4a0bf8f592f88623b3e457ec86d"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual.download]]
    sha256 = "59318e18563a2fcc96bbb2fa4aaf0ffbd7d8c644f87b3a6ec7b5d8421841a685"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "3e1fab3b4539e361cac8d7a83f39393e47f45e61"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual.download]]
    sha256 = "0f92f79bc1ef7cb6c85a6cc5f1914a2c599ffea6878affaf511d250e13e3584d"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "33a6c6d6fc9f5eb9bfc303c3d2b7326d5e93e0de"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual.download]]
    sha256 = "a1df3e0d65f3a7953ffb8b7001dc5b0ba07e1094ce7c5234448f07b734fe825e"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"

[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "1c38c82ff0de3fdab624514a23b5cdca63e04969"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "7d9dcb7b334c3b8dbd6194c1d7456f5ab7dc40f8e9c46ff3ddef16c125797e0b"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "645be517534f4d9c2f7d475c8e1f43b0746644f5"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "d109c63cc65eed0ed941a351483500bd145c851d49ba7006f90132ed76f9c001"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "ed269196e13dbcf560b710a62976a5a5eb3caf1f"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "2e18a7325b34b118238c3d5cafadb7f44fe3bb83a2cbee6115c7bfb93c9646cc"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"

[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "6fad2bf1126c6d7e78c103837840b1e87ca660a6"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "4ec1e6e39c96904f80376d81e40ed414e5e2fba08a9b287016b363d87ce881dd"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "667527420069fb4da2f67780d9dcc67ef3d18436"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "6bafae582398c223d9917caf8dab1aae810876c0bd0773577c45a62c772b7102"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "da3c8ab4edf2dd9e464298a69dce5418947fb619"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "4fc06ddfa4e18a196b4fb00fad03871ba2fb2e7e49cf3d3bf4eaefd1d230965e"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
