[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "22d86669dda41fcc25513450c82b392856b568fa"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual.download]]
    sha256 = "0660974c5f594e8bc0ee25ba2e06061c54df500d80ffbd767154378dd5ce17b8"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "c5262e8f832cf7d61ef89f203268f825782318a8"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual.download]]
    sha256 = "21767e0a81f222634a40abb7b78cd238a7b23c8fdedd939e4f8ed65bb3316211"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "33a6c6d6fc9f5eb9bfc303c3d2b7326d5e93e0de"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual.download]]
    sha256 = "2f8dd71167b34c3a6dd4687efecd125ec9c54a9e1aef77507328143087063f20"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "9f4b793deb1549af3b8e5370c64fd960fb5933c6"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual.download]]
    sha256 = "4b0e99826ec1127c075d78d38aff0aea68da97ca00dc89f4596ffdd51c24242b"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"

[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "fee8c4a16e55246664f33f52763aed3bca71db0d"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "2153225bc9417fd34356918d48d2b5c80fcd9a7447f042b1699a9f545c719fc6"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "e84e3cf7f2a2a8b7543fcfabe43a0237256f0fc1"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "166230ec8e665bbbd8867ce2d1fa67103618aafb896c401967993d681d193231"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "e5da2cbdb6e6d0d793d470e9b81d32e35c3cc0d2"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "49e1cf6d9bf02952b1c999d8ed466e46aca0d4b5cf5d08ea90afcbee4865ed4a"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "cc0626970e8adacdc3852e45b81749c9ee774b17"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "1269ad06b07b58163a8ef140ab9ec6b765d87deb716223a1ddc7b77c037583f4"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"

[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "39c18a5363d4d3a632ec5abbfad53d91af0da77a"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "5ab453784b12676102e4190feebb0daf3e026245e5050529b52955cd611cfd38"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "372afd5a1209ae75fdff39f46b3861cc5bbac8e7"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "020af7e13d2fb4ef1f4e65d65675c197a293f94010e080c76c5e74371daae5fc"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "2fbb5aeee7791b65fb48dbca30cab4c97941a7c5"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "e93841f2dd4f8629cf85398e45fc566c06787957a1c7679aacb74989f5b6be21"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b5655743bef6c4fdaabb6873060b485cb484b2f5"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "88f8cf3d9d7667cc3fe0ba1cf1c4194184c4b1b9744d585a6b9f98490edcc1bb"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_arch+aarch64.tar.gz"
