[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "04ce07db16ba80840c3796c4412ce89d3f1b3e8e"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"
target_os_version = "20.0.0"

    [[GCCBootstrapManual.download]]
    sha256 = "7e5a004c760295f795c5801dc455187683d7ee86d44a9cda998357fff2a2dfd6"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "66e369866e2ac883f0bc536e9afbe6db2efb04b3"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"
target_os_version = "20.0.0"

    [[GCCBootstrapManual.download]]
    sha256 = "380e2321a84ef230e5698a716de8f123428f229d6c4f6e3e58c10f64d1bd7ed7"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "09a7f7cc968aff5942ac2431f8805a036f533d9a"
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"
target_os_version = "14.1.0"

    [[GCCBootstrapManual.download]]
    sha256 = "4c016f7d84f9dadbe4b58e42e2085d7ac914b404a693c4e5d833a1f7dfab7424"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_os_version+14.1.0-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual]]
arch = "x86_64"
git-tree-sha1 = "6843d357a99edcfc750f4e9c261650c432756bac"
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"
target_os_version = "14.1.0"

    [[GCCBootstrapManual.download]]
    sha256 = "2d5d610c85fdc5d119156a1c03e3d7b40e5470b1e01a539bb467d2ec5cc6d20d"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_os_version+14.1.0-target_arch+aarch64.tar.gz"

[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "98a9ea3468d55cba2766846fa8701f3fb39d3eb5"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"
target_os_version = "20.0.0"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "fca577a4d2e44d0dc22864b1be75531c3994860270ac797e3fcfe7251af6fce1"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "c6342ab8ae397d4d45588bb60f838484d30bd6de"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"
target_os_version = "20.0.0"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "3b1fe43189ffe6d953c2fe7ef00bed11a21f0c2c8a8f8b529317dc9facfcb1e2"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "57aeda978c723ba3d9d7cd4c210cf3d0fd9f1a3f"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"
target_os_version = "14.1.0"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "3670573bd1193d5d89cebd414f7cc704039c74f5549836f74401ae07a7ce20b8"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_os_version+14.1.0-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-build_log]]
arch = "x86_64"
git-tree-sha1 = "22a10c478a2e41617b7a458d121ef1dc3db3c6f6"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"
target_os_version = "14.1.0"

    [[GCCBootstrapManual-build_log.download]]
    sha256 = "f0adc12f322f99f2ec5ad2608c154c8b61ecb5af26b48f004257d91b1e84f676"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-build_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_os_version+14.1.0-target_arch+aarch64.tar.gz"

[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d5a404bc5ad18eafe164ff143e99f3c4e1f3d43b"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "macos"
target_os_version = "20.0.0"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "d427b47934fa85cc0b1b4f48d505ab73cce66b4e49629b539dddea2b7586ae55"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "d79f6aed3ee548ea9bd007546caa6b4f3718891c"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "macos"
target_os_version = "20.0.0"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "4564f26bc2e2f5c92dc5068b87acb696ef49b409a26cbb75253cb03988a8c303"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+macos-target_os_version+20.0.0-target_arch+aarch64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "3528f9a262e891bcc3c28b6ee9df906c926e49dc"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "x86_64"
target_os = "freebsd"
target_os_version = "14.1.0"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "a5206986211d6526eea035c370d15d741662ea3df178ca6388e328287f41649d"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_os_version+14.1.0-target_arch+x86_64.tar.gz"
[[GCCBootstrapManual-extract_log]]
arch = "x86_64"
git-tree-sha1 = "5cacff95832a0ee77a1c3f467b809ac66c34f4e9"
lazy = true
libc = "glibc"
os = "linux"
target_arch = "aarch64"
target_os = "freebsd"
target_os_version = "14.1.0"

    [[GCCBootstrapManual-extract_log.download]]
    sha256 = "22e1e7a34f1c2dbf70e527f727652c6662e83dd98ad8245d08c2957f4f113f5a"
    url = "https://github.com/staticfloat/GCCBootstrapManual_jll.jl/releases/download/v14.2.0-GCCBootstrap-x86_64-linux-gnu/GCCBootstrapManual-extract_log-v14.2.0-x86_64-linux-gnu-target_os+freebsd-target_os_version+14.1.0-target_arch+aarch64.tar.gz"
